# Generated by Django 4.1.7 on 2023-03-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('input_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('input_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('input_return_date', models.DateField(blank=True, null=True)),
                ('input_return_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('input_return_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('input_adjustment_date', models.DateField(blank=True, null=True)),
                ('input_adjustment_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('input_adjustment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('output_date', models.DateField(blank=True, null=True)),
                ('output_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('output_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('output_return_date', models.DateField(blank=True, null=True)),
                ('output_return_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('output_return_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('output_adjustment_date', models.DateField(blank=True, null=True)),
                ('output_adjustment_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('output_adjustment_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('previous_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('previous_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('actual_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('actual_quantity', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Transaction detail',
                'verbose_name_plural': 'Transaction details',
                'ordering': ['summary', 'product_conversion'],
            },
        ),
        migrations.CreateModel(
            name='TransactionNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Purchase'), (2, 'Sale'), (3, 'Sale return'), (4, 'Purchase return'), (5, 'Positive adjustment'), (6, 'Negative adjustment'), (7, 'Positive value adjustment'), (8, 'Negative value adjustment')], default=1)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Transaction number',
                'verbose_name_plural': 'Transaction numbers',
                'ordering': ['transaction_type'],
            },
        ),
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Purchase'), (2, 'Sale'), (3, 'Sale return'), (4, 'Purchase return'), (5, 'Positive adjustment'), (6, 'Negative adjustment'), (7, 'Positive value adjustment'), (8, 'Negative value adjustment')], default=1)),
                ('document', models.CharField(max_length=20)),
                ('source_document', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries_area', to='accounting.area')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries_customer', to='commercial.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries_supplier', to='commercial.supplier')),
            ],
            options={
                'verbose_name': 'Transaction summary',
                'verbose_name_plural': 'Transaction summaries',
                'ordering': ['transaction_type', 'document'],
            },
        ),
    ]
