# Generated by Django 4.1.7 on 2023-03-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='product_conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_product', to='commercial.productconversion'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_summary', to='accounting.transactionsummary'),
        ),
        migrations.AddField(
            model_name='stock',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_area', to='accounting.area'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_location', to='accounting.location'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_product', to='commercial.product'),
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounting.area'),
        ),
        migrations.AddField(
            model_name='area',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='accounting.store'),
        ),
    ]
