# Generated by Django 4.1.7 on 2023-03-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10)),
                ('company_description', models.CharField(max_length=150)),
                ('company_address', models.CharField(blank=True, max_length=150, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='logos')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
