# Generated by Django 4.1.7 on 2023-03-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=30, verbose_name='Description')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Customer category',
                'verbose_name_plural': 'Customer categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=150, verbose_name='Description')),
                ('increment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Increment')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FamilyActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Family activity',
                'verbose_name_plural': 'Family activities',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Family group',
                'verbose_name_plural': 'Family groups',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=150, verbose_name='Description')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_family', to='commercial.family')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_measurement', to='commercial.measurement')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=150, verbose_name='Description')),
                ('owner', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Owner')),
                ('landline', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landline')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile phone')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('value', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_measurement', to='commercial.measurement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_product', to='commercial.product')),
            ],
            options={
                'verbose_name': 'Product conversion',
                'verbose_name_plural': 'Product conversions',
                'ordering': ['product'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families_activity', to='commercial.familyactivity'),
        ),
        migrations.AddField(
            model_name='family',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families_group', to='commercial.familygroup'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created date')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Edited date')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('description', models.CharField(db_index=True, max_length=150, verbose_name='Description')),
                ('owner', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Owner')),
                ('landline', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landline')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile phone')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='commercial.customercategory')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['code'],
            },
        ),
    ]
